### ISSUE TITLE
Übersicht der verfügbaren Testzentren nach Antrag

### ISSUE THREAD

**Issue by marcfreiheit** [mlichtblau/wirvsvirus#16]
Als Patient  
möchte ich eine 'Liste' verfügbarer Testzentren aufgelistet bekommen  
damit ich mich auf die Warteliste eines passenden Testzentrums setzen kann oder mich anderweitig bei dem Testzentrum melde und  
damit ich mich nicht bei Testzentren melde, dessen Kriterien ich nicht erfülle

## Problembeschreibung

Verschiedene Testzentren haben unterschiedliche Anforderungen zur Durchführung eines Testen. 

## Lösungsansatz

Wir schlagen vor, dass wir auf Basis der [Anamnese des Patienten](#15) eine Auswahl an verfügbaren und passenden Testzentren erstellen. Dabei erhält der Patient allgemeine Informationen und Kontaktdaten zu jedem Testzentrum. Des Weiteren kann er sich für ein Zentrum entscheiden und sich dort auf die [Warteliste setzen](#20).

## Akzeptanzkriterien

- [ ] Ich sehe eine Liste verfügbarer Testzentren in meinen Nähe
- [ ] Ich sehe Kontakt- und Adressinformationen sowie Öffnungszeiten zu jedem Testzentrum
- [ ] Ich sehe die Testzentren auf einer Karte
- [ ] Ich erhalte allgemeine Kontaktstellen für Corona falls kein Testzentrum in meine Nähe für mich zutreffend ist
- [ ] Ich kann die App schließen bzw. die Internetseite verlassen und erhalte die gleiche Übersicht, wenn ich die App wieder öffne bzw. die Seite wieder besuche

## Out of Scope

- [ ] Ich kann mich auf die [Warteliste eines Testzentrums setzen](#20).
- [ ] Ich sehe die geschätzte [Wartezeit eines Testzentrums](#35)
- [ ] Ich sehe die [Auslastung des Testzentrums](#36)
