### ISSUE TITLE
Wartelisten Übersicht

### ISSUE THREAD

**Issue by marcfreiheit** [mlichtblau/wirvsvirus#18]
Als Patient  
möchte ich nach [erfolgreicher Anmeldung auf einer Warteliste](#20) meinen Wartelistenplatz und die Auslastung des Testzentrums einsehen können  
damit ich meine Wartezeit abschätzen kann

## Problembeschreibung

Aufgrund der vielen Anträge können Patienten den Überblick über ihren Antrag verlieren.

## Lösungsansatz

Wir schlagen vor den Patienten regelmäßig über Änderungen an seinem Wartelistenplatz zu informieren. Dafür sollte dieser eine Übersichtsseite mit Informationen rund um seinen Wartelistenplatz und die Auslastung des Testzentrums haben.

## Akzeptanzkriterien

- [ ] Ich sehe eine [geschätzte Wartezeit](#35)
- [ ] Ich sehe die [Auslastung des Testzentrums](#36)
- [ ] Ich sehe die Kontakt- und Adressinformationen des Testzentrums
- [ ] Ich sehe eine Information, dass die Information nicht bindend sind und sich auch kurzfristig aufgrund von Notfällen ändern können. Des Weiteren werde ich darüber informiert, dass aufgrund der aktuellen Situation mit Verzögerungen zu rechnen ist.

## Out of Scope

- [ ] Ich werde über [Änderungen meines Status benachrichtigt](#14)
- [ ] Ich kann eine [verspätete Ankunft](#23) im Testzentrum melden
- [ ] Ich kann meinen [Termin absagen](#22)
- [ ] Ich kann meinen aktuellen Wartelistenplatz aufgeben und das [Testzentrum wechseln](#19)

**Comment by pia-francesca** [comment]
Was ist mit Auslastung des Testzentrums gemeint?

Welche Art von Kontaktinformationen für das Testzentrum sind sinnvoll? (Telefon? Chat?)
