### ISSUE TITLE
Testzentrum wechseln

### ISSUE THREAD

**Issue by marcfreiheit** [mlichtblau/wirvsvirus#19]
Als Patient  
möchte ich meinen Wartelistenplatz aufgeben können und das Testzentrum wechseln  
z.B. wenn sich die Schwere meiner Symptome verändert hat und ich eine intensivere bzw. dringendere Betreuung benötige.

## Problembeschreibung

Bei Verschlimmerung oder Verbesserung von Symptomen, bei einem Standortwechsel, zur Korrektur von Falschauswahl oder um auf neu eröffnetes Testzentrum zu wechseln.

## Lösungsansätze

Wir wollen dem Patienten die Möglichkeit bieten, seinen Wartelistenplatz aufzugeben und sich bei einem anderen Testzentrum auf die Warteliste zu setzen.

## Akzeptanzkriterien

- [ ] Ich erhalte die Information, dass mein aktueller Wartelistenplatz damit unwiderruflich verloren geht
- [ ] Ich erhalte eine Liste passender Testzentren auf Basis meiner [Anamnese](#15)
- [ ] Ich kann ein neues Testzentrum auswählen und [registriere mich damit auf die Warteliste](#20)
- [ ] Alternativ kann ich meinen [Termin absagen](#22) und damit mich nur von der Warteliste setzen, ohne mich auf eine neue zu setzen

## Out of Scope

**Comment by pia-francesca** [comment]
Wäre es in diesem Fall einfacher seinen Platz aufzugeben und von vorne zu beginnen? Wenn sich die Symptome verschlimmert haben wird man ja eh noch einmal die meisten Fragen durchgehen müssen. Wenn man dann noch seinen Platz in der Warteschlange verliert, sehe ich hier wenig Vorteil.

Mit einer generellen Verschlimmerung der Symptome ist wohl in vielen Fällen zu rechnen, da sich die Patienten hoffentlich im Anfangsstadium der Krankeheit in die Schlange stellen.

Bei einer rapiden Verschlimmerung der Symptome (beispielsweise anzeichen von schlechter Sauerstoffversorgung durch Atemnot oder sehr hohem Fieber) sollte auf den direkten Kontakt zu einem Arzt hinweisen werden, da möglicherweise eine stationäre Aufnahme des Pt nötig ist.
