### ISSUE TITLE
Registrierung auf Warteliste

### ISSUE THREAD

**Issue by marcfreiheit** [mlichtblau/wirvsvirus#20]
Als Patient  
möchte ich mich auf die Wartliste eines Testzentrums setzen können  
um mich dort auf einen Test zu bewerben

## Problembeschreibung

Patienten müssen auf eigenen Verantwortung sich auf Wartelisten der Testzentren registrieren können. Dabei sollten sie sich nur auf Testzentren bewerben können, die auf Basis ihrer [Anamnese](#15) empfohlen werden.

## Lösungsansätze

Wir schlagen vor, dass sich der Patient nach erfolgreicher Anamnese auf die Warteliste einer

## Akzeptanzkriterien

- [ ] Nach der [Anamnese](#15) kann ich mich auf die Warteliste eines der [vorgeschlagenen Testzentren](#16) setzen lassen
- [ ] Ich muss die [Richtigkeit meiner Angaben bestätigen](#21)
- [ ] Ich erhalte eine [Wartelistennummer](#18), mit welcher ich mich bei Ankunft beim Personal authentifiziere
- [ ] Ich erhalte eine Information über die geschätzte Wartezeit bei diesem Testzentrum
- [ ] Ich kann mich nur auf eine einzige Warteliste setzen lassen
  - [ ] Ich sehe eine Information, dass ich mich nur auf einen Warteplatz registrieren kann

## Out of Scope

- [ ] Ich kann meinen [Wartelistenplatz aufgeben und mich in einem anderen Testzentrum bewerben](#19)
- [ ] Ich kann meinen [Test absagen und mich von der Warteliste herunternehmen](#22)
