### ISSUE TITLE
Anträge auf Testzentren annehmen

### ISSUE THREAD

**Issue by marcfreiheit** [mlichtblau/wirvsvirus#32]
Als Gesundheitsamt  
möchte ich Anträge auf die Eröffnung von Testzentren prüfen und annehmen  
um den zugehörigen Personen Zugang zur Plattform zu ermöglichen.

## Problembeschreibung

Die Registrierungen für Testzentren müssen auf Richtigkeit und Vollständigkeit geprüft werden. Diese Prüfung soll im Idealfall von einer offiziellen Stelle durchgeführt werden. Die Errichtung und Führung von Testzentren ist zurzeit sehr dezentral organisiert. Unterschiedliche Bundesländer verfolgen unterschiedliche Strategien und haben eigene Anforderungen. 

Wir rechnen auch mit der Registrierung von nicht offiziellen Testzentren. Diesen wollen wir in COVID-Q keine Plattform bieten und deshalb sollen alle Anträge geprüft werden.

## Lösungsvorschlag

Wir wollen einer offiziellen Prüfungsstelle (wie z.B. dem Gesundheitsamt) einen Zugang zur Plattform bieten, mit welchem sie die Testzentren in Deutschland pflegen können. Sie sollten auch dafür zuständig sein Anträge von Testzentren zu prüfen und diese annehmen bzw. [ablehnen](#31) zu können.

## Akzeptanzkriterien

- [ ] Ich kann alle Daten des [Antrages einsehen](#2)
- [ ] Ich kann die Daten des Antrages korrigieren
- [ ] Ich sehe die Kontaktdaten des Antragstellers um mich im Falle von Rückfragen an ihn zu wenden
- [ ] Nach Annahme des Antrages erhält der Antragsteller eine [Benachrichtigung](#30)

## Out of Scope

- [ ] Anträge können auch [abgelehnt](#31) werden. Damit wird dem Antragsteller der Zugriff auf die Plattform verweigert.

## Offene Fragen

- [ ] Wer übernimmt die Prüfung von Testzentren. Besteht die Möglichkeit eine offizielle Stelle wie z.B. die Landkreise bzw. Bundesländer oder das Gesundheitsamt einzubinden?

**Comment by pia-francesca** [comment]
Welche Informationen müssen für die einzelnen Testzentren definiert werden?
- Auswahlkriterien für Patienten
- Öffnungszeiten
- ...

Wann werden die Testzentren über Ihre Registrierung informiert/ bekommen Ihre ID und PIN?
