### ISSUE TITLE
Gemeldetes Testzentrum 'claimen'

### ISSUE THREAD

**Issue by marcfreiheit** [mlichtblau/wirvsvirus#8]
Als Leiter eines Testzentrums  
möchte ich Anspruch auf ein bestehendes Testzentrum  [Anmeldung](#2) melden  
um die zentrale Warteliste auch für mein Zentrum zu benutzen und  
um die Informationen an die wartenden Patienten herzuschicken

## Problembeschreibung

Auf Basis von Medien und offiziellen Veröffentlichen [verwalten Plattform-Admins die Testzentren](#29). Die _passiven_ Testzentren bieten den Patienten nicht den vollen Funktionsumfang und dienen nur als reine Informationsquelle. 

## Lösungsansatz

Wir wollen Leitern die Möglichkeit geben, dass sie passive Testzentren für die Benutzung auf der Plattform freischalten. Dabei sollen sie Informationen zum Testprozess, ihren Kapazitäten und ihrer aktuellen Auslastung hinterlegen.

## Akzeptanzkriterien

- [ ] Ich kann bei der [Anmeldung](#2) ein bereits gemeldetes Testzentrum auswählen
- [ ] Ich kann keine bereits bestätigten und aktiven Testzentren auswählen(, weil diese bereits durch jemand anderen verifiziert werden)

## Out of Scope

- [ ] Plattform-Administratoren [verwalten die Liste von Testzentren](#29)
- [ ] Ich kann den [Status meiner Registrierung](#30) einsehen
